name: CI
on:
  pull_request: {}
  push: { branches: [master] }

jobs:
  requestActivationFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Request manual activation file
        uses: ./
        id: getManualLicenseFile
        with:
            entrypoint: /request_activation.sh

      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
            name: Manual Activation File
            path: ${{ steps.getManualLicenseFile.outputs.filePath }}
  

  testRunnerInEditMode:
    name: Test edit mode 📝
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2019 }}   
      #UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2020 }}   
      #UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2021}}   
      #UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2022 }}   
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Activate license
        uses: ./
        with:
          entrypoint: /activate.sh

      # Configure test runner
      - name: Run tests
        uses: ./
        with:
          args: -runTests -projectPath .
          workdir: unity-project-with-correct-tests
      
      # no need to return license for personal licenses
      #- name: Return license
      #  if: always()
      #  uses: ./
      #  with:
      #    args: -returnlicense -quit      

